spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    password: akuna_std
    username: akuna_std
    url: jdbc:postgresql://localhost:7777/akuna
  jpa:
    properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
          default_schema: akuna_std
          temp:
            use_jdbc_metadata_defaults: false
    hibernate:
      ddlAuto: create-drop
    show-sql: true

akuna.security.jwc:
 tokenExpirationTime: 15 # Number of minutes
 refreshTokenExpirationTime: 60 # Minutes
 tokenIssuer: http://akuna.com
 tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

server:
  port: 8181
