## Spring Boot configuration
#spring:
#  profiles:
#    active: google
## Spring Security configuration
#security:
# oauth2:
#   client:
#     clientId: 968258277997-3dbefpibl2ojob9dmb7ovedetuc637r1.apps.googleusercontent.com
#     clientSecret: E4cfj_2B9AhLFD-pQUsey6cp
#     accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#     userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#     clientAuthenticationScheme: form
#     scope:
#             - openid
#             - email
#             - profile
#   resource:
#     userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#     preferTokenInfo: true
# Server configuration
server:
  port: 8181