spring:
  profiles:
    active: "dev"

akuna.security.jwc:
 tokenExpirationTime: 5 # Number of minutes
 refreshTokenExpirationTime: 60 # Minutes
 tokenIssuer: http://akuna.com
 tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

server:
  port: 8181

