spring:
    datasource:
        driver-class-name: org.h2.Driver
        username: "sa"
        password: "sa"
        url: jdbc:h2:file:~/test
    h2:
        console:
          enabled: true
          path: /h2
    jpa:
            properties:
               hibernate:
                  dialect: org.hibernate.dialect.H2Dialect
                  temp:
                    use_jdbc_metadata_defaults: false
            hibernate:
              ddlAuto: create-drop
            show-sql: true